version: "3"
services:
  keycloak:
    image: 'jboss/keycloak'
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin-test
      - KEYCLOAK_PASSWORD=admin-test
      - JDBC_PARAMS='connectTimeout=30'
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=easybookmark
      - DB_USER=root
      - DB_PASSWORD=root
      - JGROUPS_DISCOVERY_PROTOCOL=JDBC_PING
      - JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500
    depends_on:
        - mariadb
  mariadb:
      image: mariadb
      ports: 
        - "3306:3306"
      volumes:
        - data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: easybookmark
        MYSQL_USER: bookmark
        MYSQL_PASSWORD: bookmark
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
volumes:
  data:
    driver: local